import pandas as pd
import glob
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

print("[*] Phase 1: Merging CSV Files...")
# Find all the data files generated by your factory
all_files = glob.glob("data_*_vs_*_run*.csv")

if not all_files:
    print("[-] No CSV files found. Check your directory.")
    exit()

# Read and concatenate all files into one massive DataFrame
df_list = [pd.read_csv(f) for f in all_files]
master_df = pd.concat(df_list, ignore_index=True)

# Drop any rows where perf failed to collect data (NaN values)
master_df = master_df.dropna()

print(f"[+] Successfully merged {len(all_files)} files into {len(master_df)} total samples.")
master_df.to_csv("master_dataset.csv", index=False)

print("\n[*] Phase 2: Preparing Data for Machine Learning...")
# Create our Target Label (Y): 0 = Safe, 1 = Under Attack
master_df['is_under_attack'] = master_df['attacker'].apply(lambda x: 0 if x == 'none' else 1)

# Define our Features (X): The signals the model will use to detect the attack
features = [
    'IPC', 
    'Total_MB_per_sec', 
    'cache_dominance_score', 
    'LLC-load-misses', 
    'LLC-loads'
]

X = master_df[features]
y = master_df['is_under_attack']

# Split the data: 80% for training the brain, 20% for testing how smart it is
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("[*] Phase 3: Training the Random Forest Classifier...")
# We use a Random Forest because it is highly resistant to overfitting and explains its decisions well
clf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
clf.fit(X_train, y_train)

print("\n[+] Model Evaluation on Test Data:")
# Test the model on the 20% of data it has never seen before
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred, target_names=['Safe (0)', 'Under Attack (1)']))

print("\n[*] Feature Importance (What is the model paying attention to?):")
# This tells us which hardware counters were the most useful for detecting the noisy neighbor
importances = clf.feature_importances_
for feature, importance in zip(features, importances):
    print(f" - {feature}: {importance * 100:.2f}%")

import joblib
joblib.dump(clf, 'rf_model.pkl')
print("[+] Model saved to rf_model.pkl")
